# -*- coding: utf-8 -*-
"""Ejemplo ayudantia 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1-Bsgm2oEU7uCwBX7NskFbgPz9rawrmbm

# **Primer Ejercicio de ayudantia - ICH3424**



```
# import numpy as np
z=5*4
print(z)
```
"""

#Importamos librerias a utilizar
import numpy as np
import matplotlib.pyplot as plt

dx=0.1
x=np.arange(0,2*np.pi+dx,dx)
y=np.sin(x)

#graficamos

plt.plot(x,y)
plt.xlabel('Eje X')
plt.ylabel('Eje Y')

plt.show()

# Como crear una funcion

def numerosqrt(a):
  resultado=np.sqrt(a)
  return resultado

  b=numerosqrt(4)
  print(b)

lista1 = [1,2,3,4,5,6,12]
lista2 = [2,3,4,5,6,7,8]

print(np.diff(lista1))

plt.plot(lista1,lista2,'r')